ALTER TABLE tenants ADD COLUMN IF NOT EXISTS zapsign_token TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS cora_id TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS cora_cert TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS cora_key TEXT;
